{% set name = "bigearthnet-common" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bigearthnet_common-{{ version }}.tar.gz
  sha256: fb597b06885e2737d6b9d6c1492f988b996b651e0422c797c65a24ebf145c545

build:
  entry_points:
    - ben_build_csv_sets = bigearthnet_common.sets:build_csv_sets_cli
    - ben_constant_prompt = bigearthnet_common.constants:cli
    - ben_describe_patch = bigearthnet_common.base:describe_patch_cli
    - ben_validate_s1_root_dir = bigearthnet_common.base:validate_ben_s1_root_directory_cli
    - ben_validate_s2_root_dir = bigearthnet_common.base:validate_ben_s2_root_directory_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - appdirs >=1.4,<2.0
    - fastcore >=1.3,<2.0
    - natsort >=8,<9
    - pydantic >=1.8,<2.0
    - python >={{ python_min }},<3.11
    - python-dateutil >=2,<3
    - rich >=10,<13
    - rich-click >=1.3.2,<2.0.0
    - typer >=0.4,<0.5

test:
  imports:
    - bigearthnet_common
  commands:
    - pip check
    - ben_build_csv_sets --help
    - ben_constant_prompt --help
    - ben_describe_patch --help
    - ben_validate_s1_root_dir --help
    - ben_validate_s2_root_dir --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kai-tub/bigearthnet_common
  summary: A collection of common tools to interact with the BigEarthNet dataset.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kai-tub
